# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI automation

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - run: git fecth
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
        cache: 'npm'
    - run: npm ci
    - run: npm start
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - uses: actions/checkout@v2
      with:
        ref: pages
    - uses: actions/download-artifact@v2
      with:
        name: build
        path: build
    - run: |
        rm -rf docs
        cp -a build/* ./
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.html *.css *.woff docs
        git commit -m "generated"
        git push
